name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: postgres
          POSTGRES_INITDB_ARGS=--lc-monetary=en_NG.UTF-8
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Run tests
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: postgres
      working-directory: ./tests
      run: |
        echo -e "\e[92mSetup virtual environment"
        sudo apt-get install python3-venv
        sudo apt-get install language-pack-en-base
        sudo dpkg-reconfigure locales
        python3 -m venv env
        . env/bin/activate
        echo -e "\e[92mUpgrade pip and install dependencies"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo -e "\e[92mRun all tests"
        chmod +x ./runtests.sh
        export PYTHONPATH=.
        ./runtests.sh
