# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Start MySQL
      uses: samin/mysql-action@v1.3
      env:
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    # Runs a single command using the runners shell
    - name: Set up virtual environment
      run: |
        pushd tests
        sudo apt-get install python3-venv
        python3 -m venv env
        . env/bin/activate
        pip install -r requirements.txt

    - name: Install protobuf
      run: |
        #! /bin/bash
        # Make sure you grab the latest version
        curl -OL https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip

        # Unzip
        unzip protoc-3.6.1-linux-x86_64.zip -d protoc3

        # Move protoc to /usr/local/bin/
        sudo cp -r protoc3/bin/* /usr/local/bin/

        # Move protoc3/include to /usr/local/include/
        sudo cp -r protoc3/include/* /usr/local/include/

        # Optional: change owner
        sudo chown $USER /usr/local/bin/protoc
        sudo chown -R $USER /usr/local/include/google

        sudo ldconfig
  
    # Runs a single command using the runners shell
    - name: Install required Python packages
      run: |
        sudo pip install protobuf

    # Runs a single command using the runners shell
    - name: Run tests
      run: |
        pip install -r requirements.txt
        chmod +x ./runtests.sh
        export PYTHONPATH=.
        ./runtests.sh